name: Experiment

on: workflow_dispatch

jobs:
  experiment:
    name: Experiment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Add dummy file
        run: echo "Experiment" > experiment.txt
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: 'experiment-${{ github.run_number }}'
          committer: 'Ivan Gabriele (Github) <ivan.gabriele+github@protonmail.com>'
          commit-message: 'ci: experiment'
          title: 'ci: experiment'
          token: ${{ secrets.GH_TOKEN }}
