name: Test & Publish

on: push

jobs:
  test:
    name: Lint & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm i
      - name: Lint
        run: npm run test:lint
      - name: Unit Test
        run: npm run test:unit

  publish:
    name: Publish to NPM & Github
    needs: test
    if: ${{ contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Publish to NPM
        run: npm publish --access=public --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup (Github)
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish to NPM
        run: npm publish --access=public --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
